import 'package:flutter/material.dart';
import '../models/custom_markdown_shortcut.dart';

class DefaultMarkdownShortcuts {
  static List<CustomMarkdownShortcut> get shortcuts => [
    CustomMarkdownShortcut(
      id: 'default_bold',
      label: 'Bold',
      iconCodePoint: Icons.format_bold.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '**',
      afterText: '**',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_italic',
      label: 'Italic',
      iconCodePoint: Icons.format_italic.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '_',
      afterText: '_',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_header',
      label: 'Headers',
      iconCodePoint: Icons.title.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '# ',
      afterText: '',
      isDefault: true,
      insertType: 'header',
    ),
    CustomMarkdownShortcut(
      id: 'default_point_list',
      label: 'Point List',
      iconCodePoint: Icons.fiber_manual_record.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '• ',
      afterText: '',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_strikethrough',
      label: 'Strikethrough',
      iconCodePoint: Icons.strikethrough_s.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '~~',
      afterText: '~~',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_bullet_list',
      label: 'Bullet List',
      iconCodePoint: Icons.format_list_bulleted.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '- ',
      afterText: '',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_numbered_list',
      label: 'Numbered List',
      iconCodePoint: Icons.format_list_numbered.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '1. ',
      afterText: '',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_checkbox',
      label: 'Checkbox',
      iconCodePoint: Icons.check_box_outline_blank.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '- [ ] ',
      afterText: '',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_quote',
      label: 'Quote',
      iconCodePoint: Icons.format_quote.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '> ',
      afterText: '',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_inline_code',
      label: 'Inline Code',
      iconCodePoint: Icons.code.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '`',
      afterText: '`',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_code_block',
      label: 'Code Block',
      iconCodePoint: Icons.integration_instructions.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '```\n',
      afterText: '\n```',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_link',
      label: 'Link',
      iconCodePoint: Icons.link.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '[',
      afterText: '](url)',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_checked_checkbox',
      label: 'Checked Checkbox',
      iconCodePoint: Icons.check_box.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '- [x] ',
      afterText: '',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_table',
      label: 'Table',
      iconCodePoint: Icons.table_chart.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '| Header | Header |\n| --- | --- |\n| ',
      afterText: ' |',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_horizontal_rule',
      label: 'Horizontal Rule',
      iconCodePoint: Icons.horizontal_rule.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '\n---\n',
      afterText: '',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_image',
      label: 'Image',
      iconCodePoint: Icons.image.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '![',
      afterText: '](url)',
      isDefault: true,
    ),
    CustomMarkdownShortcut(
      id: 'default_date',
      label: 'Current Date',
      iconCodePoint: Icons.today.codePoint,
      iconFontFamily: 'MaterialIcons',
      beforeText: '',
      afterText: '',
      isDefault: true,
      insertType: 'date',
    ),
  ];
}
