import '../models/custom_markdown_shortcut.dart';

class DefaultMarkdownShortcuts {
  static List<CustomMarkdownShortcut> get shortcuts => [
        const CustomMarkdownShortcut(
          id: 'default_bold',
          label: 'Bold',
          iconCodePoint: 0xe238,
          iconFontFamily: 'MaterialIcons',
          beforeText: '**',
          afterText: '**',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_italic',
          label: 'Italic',
          iconCodePoint: 0xe23f,
          iconFontFamily: 'MaterialIcons',
          beforeText: '_',
          afterText: '_',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_header',
          label: 'Headers',
          iconCodePoint: 0xe86f,
          iconFontFamily: 'MaterialIcons',
          beforeText: '# ',
          afterText: '',
          isDefault: true,
          insertType: 'header',
        ),
        const CustomMarkdownShortcut(
          id: 'default_point_list',
          label: 'Point List',
          iconCodePoint: 0x2022,
          iconFontFamily: 'MaterialIcons',
          beforeText: '• ',
          afterText: '',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_strikethrough',
          label: 'Strikethrough',
          iconCodePoint: 0xe257,
          iconFontFamily: 'MaterialIcons',
          beforeText: '~~',
          afterText: '~~',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_bullet_list',
          label: 'Bullet List',
          iconCodePoint: 0xe241,
          iconFontFamily: 'MaterialIcons',
          beforeText: '- ',
          afterText: '',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_numbered_list',
          label: 'Numbered List',
          iconCodePoint: 0xe242,
          iconFontFamily: 'MaterialIcons',
          beforeText: '1. ',
          afterText: '',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_checkbox',
          label: 'Checkbox',
          iconCodePoint: 0xe834,
          iconFontFamily: 'MaterialIcons',
          beforeText: '- [ ] ',
          afterText: '',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_quote',
          label: 'Quote',
          iconCodePoint: 0xe244,
          iconFontFamily: 'MaterialIcons',
          beforeText: '> ',
          afterText: '',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_inline_code',
          label: 'Inline Code',
          iconCodePoint: 0xe86f,
          iconFontFamily: 'MaterialIcons',
          beforeText: '`',
          afterText: '`',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_code_block',
          label: 'Code Block',
          iconCodePoint: 0xe86f,
          iconFontFamily: 'MaterialIcons',
          beforeText: '```\n',
          afterText: '\n```',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_link',
          label: 'Link',
          iconCodePoint: 0xe157,
          iconFontFamily: 'MaterialIcons',
          beforeText: '[',
          afterText: '](url)',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_checked_checkbox',
          label: 'Checked Checkbox',
          iconCodePoint: 0xe834,
          iconFontFamily: 'MaterialIcons',
          beforeText: '- [x] ',
          afterText: '',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_table',
          label: 'Table',
          iconCodePoint: 0xe8ef,
          iconFontFamily: 'MaterialIcons',
          beforeText: '| Header | Header |\n| --- | --- |\n| ',
          afterText: ' |',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_horizontal_rule',
          label: 'Horizontal Rule',
          iconCodePoint: 0xe0b0,
          iconFontFamily: 'MaterialIcons',
          beforeText: '\n---\n',
          afterText: '',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_image',
          label: 'Image',
          iconCodePoint: 0xe3b5,
          iconFontFamily: 'MaterialIcons',
          beforeText: '![',
          afterText: '](url)',
          isDefault: true,
        ),
        const CustomMarkdownShortcut(
          id: 'default_date',
          label: 'Current Date',
          iconCodePoint: 0xe916,
          iconFontFamily: 'MaterialIcons',
          beforeText: '',
          afterText: '',
          isDefault: true,
          insertType: 'date',
        ),
      ];
}
